version: '3.9'
name: m183_lb2
services:
    db:
      build: ./my-sql
      container_name: m183-lb2-db
      ports:
        - "3306:3306"
      environment:
        - MARIADB_ROOT_PASSWORD=Some.Real.Secr3t
        - MYSQL_INITDB_SKIP_TZINFO=1
    web:
      depends_on:
      - db
      build: ./todo-list
      container_name: m183-lb2-web
      environment:
        - DBSERVER=m183-lb2-db
      ports:
        - "1000:80"
      volumes:
        - type: bind
          source: ./todo-list
          target: /var/www/html
